version: '3'
services:
  hdb-server:
    build: ./server
  reverse-proxy:
    image: nginx:latest
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./security/website-cert.pem:/etc/ssl/certs/website-cert.pem
     - ./security/website-private-key.pem:/etc/ssl/certs/website-private-key.pem
  hdb-front-end:
     build: ./front_end/hdb-price-prediction
